
# Site Settings
title: Terapia Inspire
url: 'https://terapiainspire.com.br/'
logo: "logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Cuido da sua saÃºde emocional e espiritual 
  <br><br>
  Conflitos nos Relacionamentos, Ansiedade, DepressÃ£o e ProcrastinaÃ§Ã£o
  SessÃµes on-line ou presencial ğŸ‘‡ğŸ»
  <br><br>
  <a href="https://beacons.ai/aconsultoriainspire">beacons.ai/aconsultoriainspire</a> 
  
instagram: terapia_inspire

theme: jekyll-theme-minimal

# Tracker
analytics: G-HCHGR8VDSX

sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "UTF-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false

